default:
  image: "rust:latest"
  cache:
    paths:
      - .cargo

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

stages:
  - test

test:cargo:
  stage: test
  before_script:
    - wget -qO- https://binaries.cockroachdb.com/cockroach-v19.1.4.linux-amd64.tgz | tar -xvz
    - cp -i cockroach-v19.1.4.linux-amd64/cockroach /usr/local/bin
  script:
    - rustc --version && cargo --version
    - cargo test --all --verbose
